---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  namespace: monitoring  # change to your namespace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi  # adjust as needed

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring  # change to your namespace
spec:
  replicas: 1  # you can increase this for HA (High Availability)
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:latest  # Use a specific version if desired
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: GF_SECURITY_ADMIN_USER
          value: "admin"  # default admin user
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: "admin"  # default admin password; change it for security
        volumeMounts:
        - name: grafana-storage
          mountPath: /var/lib/grafana
      volumes:
      - name: grafana-storage
        persistentVolumeClaim:
          claimName: grafana-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring  # change to your namespace
spec:
  type: LoadBalancer  # or ClusterIP, NodePort, or Ingress, depending on your setup
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: grafana
